#Copyright (c) 2013 Will Drevo
from mtsm_backend.settings import (FIELD_FILE_SHA1, FIELD_FINGERPRINTED,
                                    FIELD_HASH, FIELD_OFFSET, FIELD_SONG_ID,
                                    FIELD_SONGNAME, FIELD_TOTAL_HASHES,
                                    FINGERPRINTS_TABLENAME, SONGS_TABLENAME,
                                    FIELD_CHUNK_ID, FIELD_EPISODE_ID, FIELD_SOUNDTRACK_ID,SOUNDTRACK_TABLENAME,
                                    FIELD_SOUNDNAME)



CREATE_FINGERPRINTS_TABLE = f"""
CREATE TABLE IF NOT EXISTS {FINGERPRINTS_TABLENAME} (
    {FIELD_HASH} BLOB NOT NULL
,   {FIELD_OFFSET} UNSIGNED INT NOT NULL
,   {FIELD_EPISODE_ID} INT NOT NULL
,   {FIELD_CHUNK_ID} INT NOT NULL
,   CONSTRAINT uq_{FINGERPRINTS_TABLENAME} UNIQUE  ({FIELD_EPISODE_ID}, {FIELD_CHUNK_ID}, {FIELD_OFFSET}, {FIELD_HASH})
);
"""

CREATE_FINGERPRINTS_TABLE_SOUNDTRACK = f"""
CREATE TABLE IF NOT EXISTS {FINGERPRINTS_TABLENAME} (
    {FIELD_HASH} BLOB NOT NULL
,   {FIELD_OFFSET} UNSIGNED INT NOT NULL
,   {FIELD_SOUNDTRACK_ID} INT NOT NULL
,   CONSTRAINT uq_{FINGERPRINTS_TABLENAME} UNIQUE  ({FIELD_SOUNDTRACK_ID}, {FIELD_HASH})
,   CONSTRAINT fk_{FINGERPRINTS_TABLENAME}_{FIELD_SOUNDTRACK_ID} FOREIGN KEY ({FIELD_SOUNDTRACK_ID}) REFERENCES {SOUNDTRACK_TABLENAME} ({FIELD_SOUNDTRACK_ID})
);
"""
CREATE_SOUNDTRACK_TABLE = f"""
CREATE TABLE IF NOT EXISTS {SOUNDTRACK_TABLENAME} (
    {FIELD_SOUNDTRACK_ID} SERIAL
,   {FIELD_SOUNDNAME} VARCHAR(250) NOT NULL
,   CONSTRAINT pk_{SOUNDTRACK_TABLENAME}_{FIELD_SOUNDTRACK_ID} PRIMARY KEY ({FIELD_SOUNDTRACK_ID})
,   CONSTRAINT uq_{SOUNDTRACK_TABLENAME}_{FIELD_SOUNDTRACK_ID} UNIQUE ({FIELD_SOUNDTRACK_ID})
);
"""

CREATE_INDEX = f"""
CREATE INDEX IF NOT EXISTS ix_{FINGERPRINTS_TABLENAME}_{FIELD_HASH} ON {FINGERPRINTS_TABLENAME}({FIELD_HASH});
"""


INSERT_SOUNDTRACK = f"""
    INSERT INTO {SOUNDTRACK_TABLENAME} (
            {FIELD_SOUNDTRACK_ID}
        ,   {FIELD_SOUNDNAME})
    VALUES (?, ?) ON CONFLICT DO NOTHING;
"""
INSERT_FINGERPRINT = f"""
    INSERT INTO {FINGERPRINTS_TABLENAME} (
            {FIELD_EPISODE_ID}
        ,   {FIELD_CHUNK_ID}
        ,   {FIELD_HASH}
        ,   {FIELD_OFFSET})
    VALUES (?, ?, quote(?), ?) ON CONFLICT DO NOTHING;
"""
INSERT_FINGERPRINT_SOUNDTRACK = f"""
    INSERT INTO {FINGERPRINTS_TABLENAME} (
            {FIELD_SOUNDTRACK_ID}
        ,   {FIELD_HASH}
        ,   {FIELD_OFFSET})
    VALUES (?, quote(?), ?) ON CONFLICT DO NOTHING;
"""

SELECT_FINGERPRINT = f"""
    SELECT {FIELD_EPISODE_ID}, {FIELD_CHUNK_ID}, {FIELD_OFFSET}
    FROM {FINGERPRINTS_TABLENAME}
    WHERE {FIELD_HASH} = decode(%s, 'hex');
"""

SELECT_DISTINCT_EPISODE_CHUNK = f"""
    SELECT DISTINCT {FIELD_EPISODE_ID}, {FIELD_CHUNK_ID} FROM {FINGERPRINTS_TABLENAME}
"""

SELECT_HASHES_EPISODE_CHUNK = f"""
    SELECT {FIELD_HASH}, {FIELD_OFFSET} FROM {FINGERPRINTS_TABLENAME}
    WHERE {FIELD_EPISODE_ID} = ? AND {FIELD_CHUNK_ID} = ?
"""

SELECT_FINGERPRINT_FROM_HASHES = f"""
    SELECT {FIELD_HASH}, {FIELD_OFFSET}, {FIELD_SOUNDTRACK_ID} FROM {FINGERPRINTS_TABLENAME}
    WHERE {FIELD_HASH} IN (%s)
"""